Add laf beta template
labring-actions/templates pull request #91
Opened 2023-10-08 09:01 UTC by HUAHUAI23

2023-10-09 03:05 UTC, maslow requested changes

2023-10-09 03:06 UTC, maslow requested changes

2023-10-09 03:06 UTC, maslow commented on template/laf.yaml
> +    domain:
域名需要是用户可选填的， 不填的话就分配一个

2023-10-10 10:57 UTC, zzjin approved these changes

2023-10-10 10:57 UTC, merged